language: rust
rust:
  - nightly
  - beta
  - 1.7.0
  - 1.6.0
  - 1.5.0
  - 1.4.0
after_success: |
  cargo doc && \
  echo '<meta http-equiv=refresh content=0;url=geohash/index.html>' > target/doc/index.html && \
  sudo pip install ghp-import && \
  ghp-import -n target/doc && \
  git push -qf https://${TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
