[package]

name = "geohash"
version = "0.1.2"
authors = [ "Ning Sun <sunng@about.me>" ]
description = "Geohash implementation for Rust."
license = "MIT"
keywords = ["geohash", "gis", "geography"]
repository = "https://github.com/sunng87/geohash.rs"
readme = "README.md"

[lib]

name = "geohash"
path = "src/lib.rs"
