[package]

name = "geohash"
version = "0.2.0"
authors = [ "Ning Sun <sunng@about.me>" ]
description = "Geohash implementation for Rust."
license = "MIT"
keywords = ["geohash", "gis", "geography"]
repository = "https://github.com/sunng87/geohash.rs"
readme = "README.md"

[dependencies]

geo = "*"
