[package]

name = "geohash"
version = "0.2.3"
authors = [ "Ning Sun <sunng@about.me>" ]
description = "Geohash implementation for Rust."
license = "MIT"
keywords = ["geohash", "gis", "geography"]
repository = "https://github.com/georust/geohash.rs"
readme = "README.md"
documentation = "https://georust.github.io/rust-geohash/"

[dependencies]

geo = "*"

[dev-dependencies]
num = "*"
